/**:
  ros__parameters:
    planning_plugin: "ompl_interface/OMPLPlanner"
    request_adapters: >-
      default_planner_request_adapters/AddTimeOptimalParameterization
      default_planner_request_adapters/CheckStartStateBounds
      default_planner_request_adapters/ValidateWorkspaceBounds
      default_planner_request_adapters/CheckConstraintViolations
    start_state_max_bounds_error: 0.1
    arm:
      planner_configs:
        - RRTConnectkConfigDefault
        - PRMkConfigDefault
      default_planner_config: RRTConnectkConfigDefault
      RRTConnectkConfigDefault:
        type: geometric::RRTConnect
        range: 0.0
      PRMkConfigDefault:
        type: geometric::PRM
        range: 0.0
